# These are supported funding model platforms

github: Excel-DNA
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=92N99RV5NQ29C&lc=US&item_name=Govert%20van%20Drimmelen&item_number=ExcelDna&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted
