using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ExcelDna.SourceGenerator.NativeAOT
{
    [Generator]
    public class Generator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is SyntaxReceiver receiver))
                return;

            context.AnalyzerConfigOptions.GlobalOptions.TryGetValue("build_property.PublishAOT", out string? publishAOT);

            string source = """
// <auto-generated/>
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace ExcelDna.SourceGenerator.NativeAOT
{
    public unsafe class AddInInitialize
    {
        [UnmanagedCallersOnly(EntryPoint = "Initialize", CallConvs = new[] { typeof(CallConvCdecl) })]
        public static short Initialize(void* xlAddInExportInfoAddress, void* hModuleXll, void* pPathXLL, byte disableAssemblyContextUnload, void* pTempDirPath)
        {
            ExcelDna.Integration.NativeAOT.IsActive = true;
            ExcelDna.Integration.NativeAOT.ExcelApplication = ExcelDna.COMWrappers.NativeAOT.Util.GetExcelApplication()!;
            ExcelDna.Integration.NativeAOT.TypeAdapter = new ExcelDna.COMWrappers.NativeAOT.TypeAdapter();

            [ADDINS]

            [FUNCTIONS]

            return ExcelDna.ManagedHost.AddInInitialize.InitializeNativeAOT(xlAddInExportInfoAddress, hModuleXll, pPathXLL, disableAssemblyContextUnload, pTempDirPath);
        }
    }
}
""";
            {
                string addIns = "";
                foreach (var i in receiver.AddIns)
                {
                    addIns += $"ExcelDna.Integration.NativeAOT.ExcelAddIns.Add(new ExcelDna.Integration.TypeHelper<{Util.GetFullTypeName(i)}>());\r\n";
                }
                source = source.Replace("[ADDINS]", addIns);
            }
            {
                string functions = "";
                foreach (var i in receiver.Functions)
                {
                    functions += $"ExcelDna.Integration.NativeAOT.MethodsForRegistration.Add(typeof({Util.GetFullTypeName(i.ContainingType)}).GetMethod(\"{i.Name}\")!);\r\n";
                }
                source = source.Replace("[FUNCTIONS]", functions);
            }

            context.AddSource($"ExcelDna.SG.NAOT.Init.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        class SyntaxReceiver : ISyntaxContextReceiver
        {
            public List<IMethodSymbol> Functions { get; } = new List<IMethodSymbol>();
            public List<ITypeSymbol> AddIns { get; } = new List<ITypeSymbol>();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is MethodDeclarationSyntax methodSyntax)
                {
                    IMethodSymbol methodSymbol = (context.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol)!;
                    if (methodSymbol.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString(fullNameFormat) == "ExcelDna.Integration.ExcelFunctionAttribute" ||
                    a.AttributeClass?.ToDisplayString(fullNameFormat) == "ExcelDna.Integration.ExcelCommandAttribute"))
                        Functions.Add(methodSymbol);
                }

                if (context.Node is ClassDeclarationSyntax classSyntax)
                {
                    if (context.SemanticModel.GetDeclaredSymbol(classSyntax) is ITypeSymbol typeSymbol)
                    {
                        if (typeSymbol.AllInterfaces.Any(i => Util.GetFullTypeName(i) == "ExcelDna.Integration.IExcelAddIn"))
                        {
                            AddIns.Add(typeSymbol);
                        }
                    }
                }
            }

            private static SymbolDisplayFormat fullNameFormat = new SymbolDisplayFormat(typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces);
        }
    }
}
