using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace ExcelDna.SourceGenerator.NativeAOT
{
    internal class MarshalGenerator
    {
        public static string GenerateFile(List<IMethodSymbol> functions, List<IMethodSymbol> commands)
        {
            string result = """
// <auto-generated/>
using System;
using System.Reflection;
using System.Threading;

#nullable enable

namespace ExcelDna.SourceGenerator.NativeAOT
{
    [DIRECT-MARSHAL-TYPE-ADAPTER]
}
""";
            return result.Replace("[DIRECT-MARSHAL-TYPE-ADAPTER]", MarshalGenerator.CreateDirectMarshalTypeAdapter(functions, commands));
        }

        private static string CreateDirectMarshalTypeAdapter(List<IMethodSymbol> functions, List<IMethodSymbol> commands)
        {
            IEnumerable<int> functionArgs = Parameters(functions);
            IEnumerable<int> commandArgs = Parameters(commands);

            string template = """
                class DirectMarshalTypeAdapter : ExcelDna.Registration.StaticRegistration.IDirectMarshalTypeAdapter
                {
                    private class XlDirectMarshalLazy
                    {
                        readonly Lazy<Delegate> _delegate;

                        public XlDirectMarshalLazy(Func<Delegate> delegateFactory)
                        {
                            _delegate = new Lazy<Delegate>(delegateFactory, LazyThreadSafetyMode.PublicationOnly);
                        }
                    
                [XlDirectMarshalLazyActs]

                [XlDirectMarshalLazyFuncs]
                    }

                    public nint GetActionPointerForDelegate(Delegate d, int parameters)
                    {
                [SwitchGetActionPointerForDelegate]
                
                        throw new NotImplementedException($"GetActionPointerForDelegate {parameters}");
                    }

                    public Type GetActionType(int parameters)
                    {
                [SwitchGetActionType]
                
                        throw new NotImplementedException($"GetActionType {parameters}");
                    }

                    public nint GetFunctionPointerForDelegate(Delegate d, int parameters)
                    {
                [SwitchGetFunctionPointerForDelegate]

                        throw new NotImplementedException($"GetFunctionPointerForDelegate {parameters}");
                    }

                    public Type GetFunctionType(int parameters)
                    {
                [SwitchGetFunctionType]

                        throw new NotImplementedException($"GetFunctionType {parameters}");
                    }

                    public Delegate CreateActionDelegate(Func<Delegate> delegateFactory, int parameters)
                    {
                        var lazyLambda = new XlDirectMarshalLazy(delegateFactory);
                        var delegateType = GetActionType(parameters);
                        var method = GetLazyAct(parameters);
                        return Delegate.CreateDelegate(delegateType, lazyLambda, method);
                    }

                    public Delegate CreateFunctionDelegate(Func<Delegate> delegateFactory, int parameters)
                    {
                        var lazyLambda = new XlDirectMarshalLazy(delegateFactory);
                        var delegateType = GetFunctionType(parameters);
                        var method = GetLazyFunc(parameters);
                        return Delegate.CreateDelegate(delegateType, lazyLambda, method);
                    }

                    private MethodInfo GetLazyAct(int parameters)
                    {
                [SwitchGetLazyAct]
                
                        throw new NotImplementedException($"GetLazyAct {parameters}");
                    }

                    private MethodInfo GetLazyFunc(int parameters)
                    {
                [SwitchGetLazyFunc]

                        throw new NotImplementedException($"GetLazyFunc {parameters}");
                    }

                [XlActDelegates]

                [XlFuncDelegates]
                }
                """;

            string result = template.Replace("[XlDirectMarshalLazyActs]",
                string.Join("\r\n", commandArgs.Select(i =>
$"public void Act{i}() => ((XlAct{i})_delegate.Value)();"
                )));

            result = result.Replace("[XlDirectMarshalLazyFuncs]",
                string.Join("\r\n", functionArgs.Select(i =>
$"public IntPtr Func{i}({ArgList(i)}) => ((XlFunc{i})_delegate.Value)({ParamList(i)});"
                )));

            result = result.Replace("[SwitchGetActionPointerForDelegate]", OptionalSwitch(
                string.Join("\r\n", commandArgs.Select(i =>
$"case {i}: return System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate<XlAct{i}>((XlAct{i})d);"
                ))));

            result = result.Replace("[SwitchGetActionType]", OptionalSwitch(
                string.Join("\r\n", commandArgs.Select(i =>
$"case {i}: return typeof(XlAct{i});"
                ))));

            result = result.Replace("[SwitchGetFunctionPointerForDelegate]", OptionalSwitch(
                string.Join("\r\n", functionArgs.Select(i =>
$"case {i}: return System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate<XlFunc{i}>((XlFunc{i})d);"
                ))));

            result = result.Replace("[SwitchGetFunctionType]", OptionalSwitch(
                string.Join("\r\n", functionArgs.Select(i =>
$"case {i}: return typeof(XlFunc{i});"
                ))));

            result = result.Replace("[SwitchGetLazyAct]", OptionalSwitch(
                string.Join("\r\n", commandArgs.Select(i =>
$"case {i}: return typeof(XlDirectMarshalLazy).GetMethod(\"Act{i}\")!;"
                ))));

            result = result.Replace("[SwitchGetLazyFunc]", OptionalSwitch(
                string.Join("\r\n", functionArgs.Select(i =>
$"case {i}: return typeof(XlDirectMarshalLazy).GetMethod(\"Func{i}\")!;"
                ))));

            result = result.Replace("[XlActDelegates]",
                string.Join("\r\n", commandArgs.Select(i =>
$"private delegate void XlAct{i}({ArgList(i)});"
                )));

            result = result.Replace("[XlFuncDelegates]",
                string.Join("\r\n", functionArgs.Select(i =>
$"private delegate IntPtr XlFunc{i}({ArgList(i)});"
                )));

            return result;
        }

        private static string ArgList(int i)
        {
            return RangeList(i, "IntPtr p");
        }

        private static string ParamList(int i)
        {
            return RangeList(i, "p");
        }

        private static string RangeList(int i, string prefix)
        {
            return string.Join(", ", Enumerable.Range(1, i).Select(k => $"{prefix}{k}"));
        }

        private static string OptionalSwitch(string body)
        {
            if (string.IsNullOrWhiteSpace(body))
                return "";

            return """
                switch (parameters)
                {
                [body]
                }
                """.Replace("[body]", body);
        }

        private static int Parameters(IMethodSymbol m)
        {
            if (Util.IsLastArrayParams(m))
                return 16;

            return m.Parameters.Count();
        }

        private static IEnumerable<int> Parameters(List<IMethodSymbol> m)
        {
            return m.Select(Parameters).Distinct().OrderBy(i => i);
        }
    }
}
