namespace ExcelDna.SourceGenerator.NativeAOT.Tests
{
    public class Generator
    {
        [Fact]
        public void Empty()
        {
            VerifyFunctions("", """
                List<Type> typeRefs = new List<Type>();
                List<MethodInfo> methodRefs = new List<MethodInfo>();






                """);
        }

        [Fact]
        public void Params()
        {
            VerifyFunctions("""
                using ExcelDna.Integration;

                namespace ExcelDna.AddIn.RuntimeTestsAOT
                {
                    public class Functions
                    {
                        [ExcelFunction]
                        public static string NativeParamsJoinString(string separator, params string[] values)
                        {
                            return string.Join(separator, values);
                        }
                    }
                }
                """, """
                List<Type> typeRefs = new List<Type>();
                ExcelDna.Integration.NativeAOT.MethodsForRegistration.Add(typeof(ExcelDna.AddIn.RuntimeTestsAOT.Functions).GetMethod("NativeParamsJoinString")!);
                typeRefs.Add(typeof(Func<string, string[], string>));
                typeRefs.Add(typeof(Func<object, string>));
                typeRefs.Add(typeof(Func<object, string[]>));
                typeRefs.Add(typeof(Func<string,object,object,object,object,object,object,object,object,object,object,object,object,object,object,object,string>));
                
                List<MethodInfo> methodRefs = new List<MethodInfo>();
                methodRefs.Add(typeof(List<string>).GetMethod("ToArray")!);






                """);
        }

        [Fact]
        public void AssemblyAttributes()
        {
            VerifyFunctions("""
                [assembly: ExcelDna.Integration.ExcelHandleExternal(typeof(System.Reflection.Assembly))]
                """, """
                List<Type> typeRefs = new List<Type>();
                List<MethodInfo> methodRefs = new List<MethodInfo>();


                ExcelDna.Integration.NativeAOT.AssemblyAttributes.Add(new ExcelDna.Integration.ExcelHandleExternalAttribute(typeof(System.Reflection.Assembly)));




                """);
        }

        [Fact]
        public void ExcelParameterConversions()
        {
            VerifyFunctions("""
                using System;
                using ExcelDna.Integration;

                namespace ExcelDna.AddIn.RuntimeTestsAOT
                {
                    public class Conversions
                    {
                        [ExcelParameterConversion]
                        public static Version ToVersion(string s)
                        {
                            return new Version(s);
                        }
                    }
                }
                """, """
                List<Type> typeRefs = new List<Type>();
                List<MethodInfo> methodRefs = new List<MethodInfo>();
                



                ExcelDna.Integration.NativeAOT.ExcelParameterConversions.Add(typeof(ExcelDna.AddIn.RuntimeTestsAOT.Conversions).GetMethod("ToVersion")!);


                """);
        }

        [Fact]
        public void ExcelReturnConversions()
        {
            VerifyFunctions("""
                using ExcelDna.Integration;

                namespace ExcelDna.AddIn.RuntimeTestsAOT
                {
                    public class TestType1
                    {
                        public string Value;

                        public TestType1(string value)
                        {
                            Value = value;
                        }
                    }

                    public class Conversions
                    {
                        [ExcelReturnConversion]
                        public static string FromTestType1(TestType1 value)
                        {
                            return value.Value;
                        }
                    }
                }
                """, """
                List<Type> typeRefs = new List<Type>();
                List<MethodInfo> methodRefs = new List<MethodInfo>();
                





                ExcelDna.Integration.NativeAOT.ExcelReturnConversions.Add(typeof(ExcelDna.AddIn.RuntimeTestsAOT.Conversions).GetMethod("FromTestType1")!);
                """);
        }

        private static void VerifyFunctions(string sourceCode, string body)
        {
            string template = """
        // <auto-generated/>
        using System;
        using System.Collections.Generic;
        using System.Reflection;
        using System.Runtime.CompilerServices;
        using System.Runtime.InteropServices;

        #nullable enable
        
        namespace ExcelDna.SourceGenerator.NativeAOT
        {
            public unsafe class AddInInitialize
            {
                [UnmanagedCallersOnly(EntryPoint = "Initialize", CallConvs = new[] { typeof(CallConvCdecl) })]
                public static short Initialize(void* xlAddInExportInfoAddress, void* hModuleXll, void* pPathXLL, byte disableAssemblyContextUnload, void* pTempDirPath)
                {
                    ExcelDna.Integration.NativeAOT.IsActive = true;
        
                    
        
        [BODY]


                    return ExcelDna.ManagedHost.AddInInitialize.InitializeNativeAOT(xlAddInExportInfoAddress, hModuleXll, pPathXLL, disableAssemblyContextUnload, pTempDirPath);
                }
            }
        }
        """;
            SourceGeneratorDriver.Verify(sourceCode, template.Replace("[BODY]", body));
        }
    }
}
