using System;
using System.Runtime.InteropServices;
using static ExcelDna.Loader.XlDirectMarshalTypes;

namespace ExcelDna.Loader
{
    class MarshalNativeAOT
    {
        public static IntPtr GetFunctionPointerForDelegate(Delegate d, XlMethodInfo methodInfo)
        {
            if (methodInfo.HasReturnType)
            {
                switch (methodInfo.Parameters.Length)
                {
                    case 0:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc0>((XlFunc0)d);
                    case 1:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc1>((XlFunc1)d);
                    case 2:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc2>((XlFunc2)d);
                    case 3:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc3>((XlFunc3)d);
                    case 4:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc4>((XlFunc4)d);
                    case 5:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc5>((XlFunc5)d);
                    case 6:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc6>((XlFunc6)d);
                    case 7:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc7>((XlFunc7)d);
                    case 8:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc8>((XlFunc8)d);
                    case 9:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc9>((XlFunc9)d);
                    case 10:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc10>((XlFunc10)d);
                    case 11:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc11>((XlFunc11)d);
                    case 12:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc12>((XlFunc12)d);
                    case 13:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc13>((XlFunc13)d);
                    case 14:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc14>((XlFunc14)d);
                    case 15:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc15>((XlFunc15)d);
                    case 16:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc16>((XlFunc16)d);
                    case 17:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc17>((XlFunc17)d);
                    case 18:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc18>((XlFunc18)d);
                    case 19:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc19>((XlFunc19)d);
                    case 20:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc20>((XlFunc20)d);
                    case 21:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc21>((XlFunc21)d);
                    case 22:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc22>((XlFunc22)d);
                    case 23:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc23>((XlFunc23)d);
                    case 24:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc24>((XlFunc24)d);
                    case 25:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc25>((XlFunc25)d);
                    case 26:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc26>((XlFunc26)d);
                    case 27:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc27>((XlFunc27)d);
                    case 28:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc28>((XlFunc28)d);
                    case 29:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc29>((XlFunc29)d);
                    case 30:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc30>((XlFunc30)d);
                    case 31:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc31>((XlFunc31)d);
                    case 32:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc32>((XlFunc32)d);
                    case 33:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc33>((XlFunc33)d);
                    case 34:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc34>((XlFunc34)d);
                    case 35:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc35>((XlFunc35)d);
                    case 36:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc36>((XlFunc36)d);
                    case 37:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc37>((XlFunc37)d);
                    case 38:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc38>((XlFunc38)d);
                    case 39:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc39>((XlFunc39)d);
                    case 40:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc40>((XlFunc40)d);
                    case 41:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc41>((XlFunc41)d);
                    case 42:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc42>((XlFunc42)d);
                    case 43:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc43>((XlFunc43)d);
                    case 44:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc44>((XlFunc44)d);
                    case 45:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc45>((XlFunc45)d);
                    case 46:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc46>((XlFunc46)d);
                    case 47:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc47>((XlFunc47)d);
                    case 48:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc48>((XlFunc48)d);
                    case 49:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc49>((XlFunc49)d);
                    case 50:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc50>((XlFunc50)d);
                    case 51:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc51>((XlFunc51)d);
                    case 52:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc52>((XlFunc52)d);
                    case 53:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc53>((XlFunc53)d);
                    case 54:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc54>((XlFunc54)d);
                    case 55:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc55>((XlFunc55)d);
                    case 56:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc56>((XlFunc56)d);
                    case 57:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc57>((XlFunc57)d);
                    case 58:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc58>((XlFunc58)d);
                    case 59:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc59>((XlFunc59)d);
                    case 60:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc60>((XlFunc60)d);
                    case 61:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc61>((XlFunc61)d);
                    case 62:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc62>((XlFunc62)d);
                    case 63:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc63>((XlFunc63)d);
                    case 64:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc64>((XlFunc64)d);
                    case 65:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc65>((XlFunc65)d);
                    case 66:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc66>((XlFunc66)d);
                    case 67:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc67>((XlFunc67)d);
                    case 68:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc68>((XlFunc68)d);
                    case 69:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc69>((XlFunc69)d);
                    case 70:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc70>((XlFunc70)d);
                    case 71:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc71>((XlFunc71)d);
                    case 72:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc72>((XlFunc72)d);
                    case 73:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc73>((XlFunc73)d);
                    case 74:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc74>((XlFunc74)d);
                    case 75:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc75>((XlFunc75)d);
                    case 76:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc76>((XlFunc76)d);
                    case 77:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc77>((XlFunc77)d);
                    case 78:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc78>((XlFunc78)d);
                    case 79:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc79>((XlFunc79)d);
                    case 80:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc80>((XlFunc80)d);
                    case 81:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc81>((XlFunc81)d);
                    case 82:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc82>((XlFunc82)d);
                    case 83:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc83>((XlFunc83)d);
                    case 84:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc84>((XlFunc84)d);
                    case 85:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc85>((XlFunc85)d);
                    case 86:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc86>((XlFunc86)d);
                    case 87:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc87>((XlFunc87)d);
                    case 88:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc88>((XlFunc88)d);
                    case 89:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc89>((XlFunc89)d);
                    case 90:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc90>((XlFunc90)d);
                    case 91:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc91>((XlFunc91)d);
                    case 92:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc92>((XlFunc92)d);
                    case 93:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc93>((XlFunc93)d);
                    case 94:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc94>((XlFunc94)d);
                    case 95:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc95>((XlFunc95)d);
                    case 96:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc96>((XlFunc96)d);
                    case 97:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc97>((XlFunc97)d);
                    case 98:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc98>((XlFunc98)d);
                    case 99:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc99>((XlFunc99)d);
                    case 100:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc100>((XlFunc100)d);
                    case 101:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc101>((XlFunc101)d);
                    case 102:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc102>((XlFunc102)d);
                    case 103:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc103>((XlFunc103)d);
                    case 104:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc104>((XlFunc104)d);
                    case 105:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc105>((XlFunc105)d);
                    case 106:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc106>((XlFunc106)d);
                    case 107:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc107>((XlFunc107)d);
                    case 108:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc108>((XlFunc108)d);
                    case 109:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc109>((XlFunc109)d);
                    case 110:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc110>((XlFunc110)d);
                    case 111:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc111>((XlFunc111)d);
                    case 112:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc112>((XlFunc112)d);
                    case 113:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc113>((XlFunc113)d);
                    case 114:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc114>((XlFunc114)d);
                    case 115:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc115>((XlFunc115)d);
                    case 116:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc116>((XlFunc116)d);
                    case 117:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc117>((XlFunc117)d);
                    case 118:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc118>((XlFunc118)d);
                    case 119:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc119>((XlFunc119)d);
                    case 120:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc120>((XlFunc120)d);
                    case 121:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc121>((XlFunc121)d);
                    case 122:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc122>((XlFunc122)d);
                    case 123:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc123>((XlFunc123)d);
                    case 124:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc124>((XlFunc124)d);
                    case 125:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc125>((XlFunc125)d);
                    case 126:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc126>((XlFunc126)d);
                    case 127:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc127>((XlFunc127)d);
                    case 128:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc128>((XlFunc128)d);
                    case 129:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc129>((XlFunc129)d);
                    case 130:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc130>((XlFunc130)d);
                    case 131:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc131>((XlFunc131)d);
                    case 132:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc132>((XlFunc132)d);
                    case 133:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc133>((XlFunc133)d);
                    case 134:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc134>((XlFunc134)d);
                    case 135:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc135>((XlFunc135)d);
                    case 136:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc136>((XlFunc136)d);
                    case 137:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc137>((XlFunc137)d);
                    case 138:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc138>((XlFunc138)d);
                    case 139:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc139>((XlFunc139)d);
                    case 140:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc140>((XlFunc140)d);
                    case 141:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc141>((XlFunc141)d);
                    case 142:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc142>((XlFunc142)d);
                    case 143:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc143>((XlFunc143)d);
                    case 144:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc144>((XlFunc144)d);
                    case 145:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc145>((XlFunc145)d);
                    case 146:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc146>((XlFunc146)d);
                    case 147:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc147>((XlFunc147)d);
                    case 148:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc148>((XlFunc148)d);
                    case 149:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc149>((XlFunc149)d);
                    case 150:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc150>((XlFunc150)d);
                    case 151:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc151>((XlFunc151)d);
                    case 152:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc152>((XlFunc152)d);
                    case 153:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc153>((XlFunc153)d);
                    case 154:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc154>((XlFunc154)d);
                    case 155:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc155>((XlFunc155)d);
                    case 156:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc156>((XlFunc156)d);
                    case 157:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc157>((XlFunc157)d);
                    case 158:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc158>((XlFunc158)d);
                    case 159:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc159>((XlFunc159)d);
                    case 160:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc160>((XlFunc160)d);
                    case 161:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc161>((XlFunc161)d);
                    case 162:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc162>((XlFunc162)d);
                    case 163:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc163>((XlFunc163)d);
                    case 164:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc164>((XlFunc164)d);
                    case 165:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc165>((XlFunc165)d);
                    case 166:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc166>((XlFunc166)d);
                    case 167:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc167>((XlFunc167)d);
                    case 168:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc168>((XlFunc168)d);
                    case 169:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc169>((XlFunc169)d);
                    case 170:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc170>((XlFunc170)d);
                    case 171:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc171>((XlFunc171)d);
                    case 172:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc172>((XlFunc172)d);
                    case 173:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc173>((XlFunc173)d);
                    case 174:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc174>((XlFunc174)d);
                    case 175:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc175>((XlFunc175)d);
                    case 176:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc176>((XlFunc176)d);
                    case 177:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc177>((XlFunc177)d);
                    case 178:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc178>((XlFunc178)d);
                    case 179:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc179>((XlFunc179)d);
                    case 180:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc180>((XlFunc180)d);
                    case 181:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc181>((XlFunc181)d);
                    case 182:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc182>((XlFunc182)d);
                    case 183:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc183>((XlFunc183)d);
                    case 184:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc184>((XlFunc184)d);
                    case 185:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc185>((XlFunc185)d);
                    case 186:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc186>((XlFunc186)d);
                    case 187:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc187>((XlFunc187)d);
                    case 188:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc188>((XlFunc188)d);
                    case 189:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc189>((XlFunc189)d);
                    case 190:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc190>((XlFunc190)d);
                    case 191:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc191>((XlFunc191)d);
                    case 192:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc192>((XlFunc192)d);
                    case 193:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc193>((XlFunc193)d);
                    case 194:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc194>((XlFunc194)d);
                    case 195:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc195>((XlFunc195)d);
                    case 196:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc196>((XlFunc196)d);
                    case 197:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc197>((XlFunc197)d);
                    case 198:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc198>((XlFunc198)d);
                    case 199:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc199>((XlFunc199)d);
                    case 200:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc200>((XlFunc200)d);
                    case 201:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc201>((XlFunc201)d);
                    case 202:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc202>((XlFunc202)d);
                    case 203:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc203>((XlFunc203)d);
                    case 204:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc204>((XlFunc204)d);
                    case 205:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc205>((XlFunc205)d);
                    case 206:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc206>((XlFunc206)d);
                    case 207:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc207>((XlFunc207)d);
                    case 208:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc208>((XlFunc208)d);
                    case 209:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc209>((XlFunc209)d);
                    case 210:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc210>((XlFunc210)d);
                    case 211:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc211>((XlFunc211)d);
                    case 212:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc212>((XlFunc212)d);
                    case 213:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc213>((XlFunc213)d);
                    case 214:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc214>((XlFunc214)d);
                    case 215:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc215>((XlFunc215)d);
                    case 216:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc216>((XlFunc216)d);
                    case 217:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc217>((XlFunc217)d);
                    case 218:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc218>((XlFunc218)d);
                    case 219:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc219>((XlFunc219)d);
                    case 220:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc220>((XlFunc220)d);
                    case 221:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc221>((XlFunc221)d);
                    case 222:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc222>((XlFunc222)d);
                    case 223:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc223>((XlFunc223)d);
                    case 224:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc224>((XlFunc224)d);
                    case 225:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc225>((XlFunc225)d);
                    case 226:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc226>((XlFunc226)d);
                    case 227:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc227>((XlFunc227)d);
                    case 228:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc228>((XlFunc228)d);
                    case 229:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc229>((XlFunc229)d);
                    case 230:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc230>((XlFunc230)d);
                    case 231:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc231>((XlFunc231)d);
                    case 232:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc232>((XlFunc232)d);
                    case 233:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc233>((XlFunc233)d);
                    case 234:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc234>((XlFunc234)d);
                    case 235:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc235>((XlFunc235)d);
                    case 236:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc236>((XlFunc236)d);
                    case 237:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc237>((XlFunc237)d);
                    case 238:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc238>((XlFunc238)d);
                    case 239:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc239>((XlFunc239)d);
                    case 240:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc240>((XlFunc240)d);
                    case 241:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc241>((XlFunc241)d);
                    case 242:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc242>((XlFunc242)d);
                    case 243:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc243>((XlFunc243)d);
                    case 244:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc244>((XlFunc244)d);
                    case 245:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc245>((XlFunc245)d);
                    case 246:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc246>((XlFunc246)d);
                    case 247:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc247>((XlFunc247)d);
                    case 248:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc248>((XlFunc248)d);
                    case 249:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc249>((XlFunc249)d);
                    case 250:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc250>((XlFunc250)d);
                    case 251:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc251>((XlFunc251)d);
                    case 252:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc252>((XlFunc252)d);
                    case 253:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc253>((XlFunc253)d);
                    case 254:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc254>((XlFunc254)d);
                    case 255:
                        return Marshal.GetFunctionPointerForDelegate<XlFunc255>((XlFunc255)d);
                }
            }
            else
            {
                switch (methodInfo.Parameters.Length)
                {
                    case 0:
                        return Marshal.GetFunctionPointerForDelegate<XlAct0>((XlAct0)d);
                    case 1:
                        return Marshal.GetFunctionPointerForDelegate<XlAct1>((XlAct1)d);
                    case 2:
                        return Marshal.GetFunctionPointerForDelegate<XlAct2>((XlAct2)d);
                    case 3:
                        return Marshal.GetFunctionPointerForDelegate<XlAct3>((XlAct3)d);
                    case 4:
                        return Marshal.GetFunctionPointerForDelegate<XlAct4>((XlAct4)d);
                    case 5:
                        return Marshal.GetFunctionPointerForDelegate<XlAct5>((XlAct5)d);
                    case 6:
                        return Marshal.GetFunctionPointerForDelegate<XlAct6>((XlAct6)d);
                    case 7:
                        return Marshal.GetFunctionPointerForDelegate<XlAct7>((XlAct7)d);
                    case 8:
                        return Marshal.GetFunctionPointerForDelegate<XlAct8>((XlAct8)d);
                    case 9:
                        return Marshal.GetFunctionPointerForDelegate<XlAct9>((XlAct9)d);
                    case 10:
                        return Marshal.GetFunctionPointerForDelegate<XlAct10>((XlAct10)d);
                    case 11:
                        return Marshal.GetFunctionPointerForDelegate<XlAct11>((XlAct11)d);
                    case 12:
                        return Marshal.GetFunctionPointerForDelegate<XlAct12>((XlAct12)d);
                    case 13:
                        return Marshal.GetFunctionPointerForDelegate<XlAct13>((XlAct13)d);
                    case 14:
                        return Marshal.GetFunctionPointerForDelegate<XlAct14>((XlAct14)d);
                    case 15:
                        return Marshal.GetFunctionPointerForDelegate<XlAct15>((XlAct15)d);
                    case 16:
                        return Marshal.GetFunctionPointerForDelegate<XlAct16>((XlAct16)d);
                    case 17:
                        return Marshal.GetFunctionPointerForDelegate<XlAct17>((XlAct17)d);
                    case 18:
                        return Marshal.GetFunctionPointerForDelegate<XlAct18>((XlAct18)d);
                    case 19:
                        return Marshal.GetFunctionPointerForDelegate<XlAct19>((XlAct19)d);
                    case 20:
                        return Marshal.GetFunctionPointerForDelegate<XlAct20>((XlAct20)d);
                    case 21:
                        return Marshal.GetFunctionPointerForDelegate<XlAct21>((XlAct21)d);
                    case 22:
                        return Marshal.GetFunctionPointerForDelegate<XlAct22>((XlAct22)d);
                    case 23:
                        return Marshal.GetFunctionPointerForDelegate<XlAct23>((XlAct23)d);
                    case 24:
                        return Marshal.GetFunctionPointerForDelegate<XlAct24>((XlAct24)d);
                    case 25:
                        return Marshal.GetFunctionPointerForDelegate<XlAct25>((XlAct25)d);
                    case 26:
                        return Marshal.GetFunctionPointerForDelegate<XlAct26>((XlAct26)d);
                    case 27:
                        return Marshal.GetFunctionPointerForDelegate<XlAct27>((XlAct27)d);
                    case 28:
                        return Marshal.GetFunctionPointerForDelegate<XlAct28>((XlAct28)d);
                    case 29:
                        return Marshal.GetFunctionPointerForDelegate<XlAct29>((XlAct29)d);
                    case 30:
                        return Marshal.GetFunctionPointerForDelegate<XlAct30>((XlAct30)d);
                    case 31:
                        return Marshal.GetFunctionPointerForDelegate<XlAct31>((XlAct31)d);
                    case 32:
                        return Marshal.GetFunctionPointerForDelegate<XlAct32>((XlAct32)d);
                    case 33:
                        return Marshal.GetFunctionPointerForDelegate<XlAct33>((XlAct33)d);
                    case 34:
                        return Marshal.GetFunctionPointerForDelegate<XlAct34>((XlAct34)d);
                    case 35:
                        return Marshal.GetFunctionPointerForDelegate<XlAct35>((XlAct35)d);
                    case 36:
                        return Marshal.GetFunctionPointerForDelegate<XlAct36>((XlAct36)d);
                    case 37:
                        return Marshal.GetFunctionPointerForDelegate<XlAct37>((XlAct37)d);
                    case 38:
                        return Marshal.GetFunctionPointerForDelegate<XlAct38>((XlAct38)d);
                    case 39:
                        return Marshal.GetFunctionPointerForDelegate<XlAct39>((XlAct39)d);
                    case 40:
                        return Marshal.GetFunctionPointerForDelegate<XlAct40>((XlAct40)d);
                    case 41:
                        return Marshal.GetFunctionPointerForDelegate<XlAct41>((XlAct41)d);
                    case 42:
                        return Marshal.GetFunctionPointerForDelegate<XlAct42>((XlAct42)d);
                    case 43:
                        return Marshal.GetFunctionPointerForDelegate<XlAct43>((XlAct43)d);
                    case 44:
                        return Marshal.GetFunctionPointerForDelegate<XlAct44>((XlAct44)d);
                    case 45:
                        return Marshal.GetFunctionPointerForDelegate<XlAct45>((XlAct45)d);
                    case 46:
                        return Marshal.GetFunctionPointerForDelegate<XlAct46>((XlAct46)d);
                    case 47:
                        return Marshal.GetFunctionPointerForDelegate<XlAct47>((XlAct47)d);
                    case 48:
                        return Marshal.GetFunctionPointerForDelegate<XlAct48>((XlAct48)d);
                    case 49:
                        return Marshal.GetFunctionPointerForDelegate<XlAct49>((XlAct49)d);
                    case 50:
                        return Marshal.GetFunctionPointerForDelegate<XlAct50>((XlAct50)d);
                    case 51:
                        return Marshal.GetFunctionPointerForDelegate<XlAct51>((XlAct51)d);
                    case 52:
                        return Marshal.GetFunctionPointerForDelegate<XlAct52>((XlAct52)d);
                    case 53:
                        return Marshal.GetFunctionPointerForDelegate<XlAct53>((XlAct53)d);
                    case 54:
                        return Marshal.GetFunctionPointerForDelegate<XlAct54>((XlAct54)d);
                    case 55:
                        return Marshal.GetFunctionPointerForDelegate<XlAct55>((XlAct55)d);
                    case 56:
                        return Marshal.GetFunctionPointerForDelegate<XlAct56>((XlAct56)d);
                    case 57:
                        return Marshal.GetFunctionPointerForDelegate<XlAct57>((XlAct57)d);
                    case 58:
                        return Marshal.GetFunctionPointerForDelegate<XlAct58>((XlAct58)d);
                    case 59:
                        return Marshal.GetFunctionPointerForDelegate<XlAct59>((XlAct59)d);
                    case 60:
                        return Marshal.GetFunctionPointerForDelegate<XlAct60>((XlAct60)d);
                    case 61:
                        return Marshal.GetFunctionPointerForDelegate<XlAct61>((XlAct61)d);
                    case 62:
                        return Marshal.GetFunctionPointerForDelegate<XlAct62>((XlAct62)d);
                    case 63:
                        return Marshal.GetFunctionPointerForDelegate<XlAct63>((XlAct63)d);
                    case 64:
                        return Marshal.GetFunctionPointerForDelegate<XlAct64>((XlAct64)d);
                    case 65:
                        return Marshal.GetFunctionPointerForDelegate<XlAct65>((XlAct65)d);
                    case 66:
                        return Marshal.GetFunctionPointerForDelegate<XlAct66>((XlAct66)d);
                    case 67:
                        return Marshal.GetFunctionPointerForDelegate<XlAct67>((XlAct67)d);
                    case 68:
                        return Marshal.GetFunctionPointerForDelegate<XlAct68>((XlAct68)d);
                    case 69:
                        return Marshal.GetFunctionPointerForDelegate<XlAct69>((XlAct69)d);
                    case 70:
                        return Marshal.GetFunctionPointerForDelegate<XlAct70>((XlAct70)d);
                    case 71:
                        return Marshal.GetFunctionPointerForDelegate<XlAct71>((XlAct71)d);
                    case 72:
                        return Marshal.GetFunctionPointerForDelegate<XlAct72>((XlAct72)d);
                    case 73:
                        return Marshal.GetFunctionPointerForDelegate<XlAct73>((XlAct73)d);
                    case 74:
                        return Marshal.GetFunctionPointerForDelegate<XlAct74>((XlAct74)d);
                    case 75:
                        return Marshal.GetFunctionPointerForDelegate<XlAct75>((XlAct75)d);
                    case 76:
                        return Marshal.GetFunctionPointerForDelegate<XlAct76>((XlAct76)d);
                    case 77:
                        return Marshal.GetFunctionPointerForDelegate<XlAct77>((XlAct77)d);
                    case 78:
                        return Marshal.GetFunctionPointerForDelegate<XlAct78>((XlAct78)d);
                    case 79:
                        return Marshal.GetFunctionPointerForDelegate<XlAct79>((XlAct79)d);
                    case 80:
                        return Marshal.GetFunctionPointerForDelegate<XlAct80>((XlAct80)d);
                    case 81:
                        return Marshal.GetFunctionPointerForDelegate<XlAct81>((XlAct81)d);
                    case 82:
                        return Marshal.GetFunctionPointerForDelegate<XlAct82>((XlAct82)d);
                    case 83:
                        return Marshal.GetFunctionPointerForDelegate<XlAct83>((XlAct83)d);
                    case 84:
                        return Marshal.GetFunctionPointerForDelegate<XlAct84>((XlAct84)d);
                    case 85:
                        return Marshal.GetFunctionPointerForDelegate<XlAct85>((XlAct85)d);
                    case 86:
                        return Marshal.GetFunctionPointerForDelegate<XlAct86>((XlAct86)d);
                    case 87:
                        return Marshal.GetFunctionPointerForDelegate<XlAct87>((XlAct87)d);
                    case 88:
                        return Marshal.GetFunctionPointerForDelegate<XlAct88>((XlAct88)d);
                    case 89:
                        return Marshal.GetFunctionPointerForDelegate<XlAct89>((XlAct89)d);
                    case 90:
                        return Marshal.GetFunctionPointerForDelegate<XlAct90>((XlAct90)d);
                    case 91:
                        return Marshal.GetFunctionPointerForDelegate<XlAct91>((XlAct91)d);
                    case 92:
                        return Marshal.GetFunctionPointerForDelegate<XlAct92>((XlAct92)d);
                    case 93:
                        return Marshal.GetFunctionPointerForDelegate<XlAct93>((XlAct93)d);
                    case 94:
                        return Marshal.GetFunctionPointerForDelegate<XlAct94>((XlAct94)d);
                    case 95:
                        return Marshal.GetFunctionPointerForDelegate<XlAct95>((XlAct95)d);
                    case 96:
                        return Marshal.GetFunctionPointerForDelegate<XlAct96>((XlAct96)d);
                    case 97:
                        return Marshal.GetFunctionPointerForDelegate<XlAct97>((XlAct97)d);
                    case 98:
                        return Marshal.GetFunctionPointerForDelegate<XlAct98>((XlAct98)d);
                    case 99:
                        return Marshal.GetFunctionPointerForDelegate<XlAct99>((XlAct99)d);
                    case 100:
                        return Marshal.GetFunctionPointerForDelegate<XlAct100>((XlAct100)d);
                    case 101:
                        return Marshal.GetFunctionPointerForDelegate<XlAct101>((XlAct101)d);
                    case 102:
                        return Marshal.GetFunctionPointerForDelegate<XlAct102>((XlAct102)d);
                    case 103:
                        return Marshal.GetFunctionPointerForDelegate<XlAct103>((XlAct103)d);
                    case 104:
                        return Marshal.GetFunctionPointerForDelegate<XlAct104>((XlAct104)d);
                    case 105:
                        return Marshal.GetFunctionPointerForDelegate<XlAct105>((XlAct105)d);
                    case 106:
                        return Marshal.GetFunctionPointerForDelegate<XlAct106>((XlAct106)d);
                    case 107:
                        return Marshal.GetFunctionPointerForDelegate<XlAct107>((XlAct107)d);
                    case 108:
                        return Marshal.GetFunctionPointerForDelegate<XlAct108>((XlAct108)d);
                    case 109:
                        return Marshal.GetFunctionPointerForDelegate<XlAct109>((XlAct109)d);
                    case 110:
                        return Marshal.GetFunctionPointerForDelegate<XlAct110>((XlAct110)d);
                    case 111:
                        return Marshal.GetFunctionPointerForDelegate<XlAct111>((XlAct111)d);
                    case 112:
                        return Marshal.GetFunctionPointerForDelegate<XlAct112>((XlAct112)d);
                    case 113:
                        return Marshal.GetFunctionPointerForDelegate<XlAct113>((XlAct113)d);
                    case 114:
                        return Marshal.GetFunctionPointerForDelegate<XlAct114>((XlAct114)d);
                    case 115:
                        return Marshal.GetFunctionPointerForDelegate<XlAct115>((XlAct115)d);
                    case 116:
                        return Marshal.GetFunctionPointerForDelegate<XlAct116>((XlAct116)d);
                    case 117:
                        return Marshal.GetFunctionPointerForDelegate<XlAct117>((XlAct117)d);
                    case 118:
                        return Marshal.GetFunctionPointerForDelegate<XlAct118>((XlAct118)d);
                    case 119:
                        return Marshal.GetFunctionPointerForDelegate<XlAct119>((XlAct119)d);
                    case 120:
                        return Marshal.GetFunctionPointerForDelegate<XlAct120>((XlAct120)d);
                    case 121:
                        return Marshal.GetFunctionPointerForDelegate<XlAct121>((XlAct121)d);
                    case 122:
                        return Marshal.GetFunctionPointerForDelegate<XlAct122>((XlAct122)d);
                    case 123:
                        return Marshal.GetFunctionPointerForDelegate<XlAct123>((XlAct123)d);
                    case 124:
                        return Marshal.GetFunctionPointerForDelegate<XlAct124>((XlAct124)d);
                    case 125:
                        return Marshal.GetFunctionPointerForDelegate<XlAct125>((XlAct125)d);
                    case 126:
                        return Marshal.GetFunctionPointerForDelegate<XlAct126>((XlAct126)d);
                    case 127:
                        return Marshal.GetFunctionPointerForDelegate<XlAct127>((XlAct127)d);
                    case 128:
                        return Marshal.GetFunctionPointerForDelegate<XlAct128>((XlAct128)d);
                    case 129:
                        return Marshal.GetFunctionPointerForDelegate<XlAct129>((XlAct129)d);
                    case 130:
                        return Marshal.GetFunctionPointerForDelegate<XlAct130>((XlAct130)d);
                    case 131:
                        return Marshal.GetFunctionPointerForDelegate<XlAct131>((XlAct131)d);
                    case 132:
                        return Marshal.GetFunctionPointerForDelegate<XlAct132>((XlAct132)d);
                    case 133:
                        return Marshal.GetFunctionPointerForDelegate<XlAct133>((XlAct133)d);
                    case 134:
                        return Marshal.GetFunctionPointerForDelegate<XlAct134>((XlAct134)d);
                    case 135:
                        return Marshal.GetFunctionPointerForDelegate<XlAct135>((XlAct135)d);
                    case 136:
                        return Marshal.GetFunctionPointerForDelegate<XlAct136>((XlAct136)d);
                    case 137:
                        return Marshal.GetFunctionPointerForDelegate<XlAct137>((XlAct137)d);
                    case 138:
                        return Marshal.GetFunctionPointerForDelegate<XlAct138>((XlAct138)d);
                    case 139:
                        return Marshal.GetFunctionPointerForDelegate<XlAct139>((XlAct139)d);
                    case 140:
                        return Marshal.GetFunctionPointerForDelegate<XlAct140>((XlAct140)d);
                    case 141:
                        return Marshal.GetFunctionPointerForDelegate<XlAct141>((XlAct141)d);
                    case 142:
                        return Marshal.GetFunctionPointerForDelegate<XlAct142>((XlAct142)d);
                    case 143:
                        return Marshal.GetFunctionPointerForDelegate<XlAct143>((XlAct143)d);
                    case 144:
                        return Marshal.GetFunctionPointerForDelegate<XlAct144>((XlAct144)d);
                    case 145:
                        return Marshal.GetFunctionPointerForDelegate<XlAct145>((XlAct145)d);
                    case 146:
                        return Marshal.GetFunctionPointerForDelegate<XlAct146>((XlAct146)d);
                    case 147:
                        return Marshal.GetFunctionPointerForDelegate<XlAct147>((XlAct147)d);
                    case 148:
                        return Marshal.GetFunctionPointerForDelegate<XlAct148>((XlAct148)d);
                    case 149:
                        return Marshal.GetFunctionPointerForDelegate<XlAct149>((XlAct149)d);
                    case 150:
                        return Marshal.GetFunctionPointerForDelegate<XlAct150>((XlAct150)d);
                    case 151:
                        return Marshal.GetFunctionPointerForDelegate<XlAct151>((XlAct151)d);
                    case 152:
                        return Marshal.GetFunctionPointerForDelegate<XlAct152>((XlAct152)d);
                    case 153:
                        return Marshal.GetFunctionPointerForDelegate<XlAct153>((XlAct153)d);
                    case 154:
                        return Marshal.GetFunctionPointerForDelegate<XlAct154>((XlAct154)d);
                    case 155:
                        return Marshal.GetFunctionPointerForDelegate<XlAct155>((XlAct155)d);
                    case 156:
                        return Marshal.GetFunctionPointerForDelegate<XlAct156>((XlAct156)d);
                    case 157:
                        return Marshal.GetFunctionPointerForDelegate<XlAct157>((XlAct157)d);
                    case 158:
                        return Marshal.GetFunctionPointerForDelegate<XlAct158>((XlAct158)d);
                    case 159:
                        return Marshal.GetFunctionPointerForDelegate<XlAct159>((XlAct159)d);
                    case 160:
                        return Marshal.GetFunctionPointerForDelegate<XlAct160>((XlAct160)d);
                    case 161:
                        return Marshal.GetFunctionPointerForDelegate<XlAct161>((XlAct161)d);
                    case 162:
                        return Marshal.GetFunctionPointerForDelegate<XlAct162>((XlAct162)d);
                    case 163:
                        return Marshal.GetFunctionPointerForDelegate<XlAct163>((XlAct163)d);
                    case 164:
                        return Marshal.GetFunctionPointerForDelegate<XlAct164>((XlAct164)d);
                    case 165:
                        return Marshal.GetFunctionPointerForDelegate<XlAct165>((XlAct165)d);
                    case 166:
                        return Marshal.GetFunctionPointerForDelegate<XlAct166>((XlAct166)d);
                    case 167:
                        return Marshal.GetFunctionPointerForDelegate<XlAct167>((XlAct167)d);
                    case 168:
                        return Marshal.GetFunctionPointerForDelegate<XlAct168>((XlAct168)d);
                    case 169:
                        return Marshal.GetFunctionPointerForDelegate<XlAct169>((XlAct169)d);
                    case 170:
                        return Marshal.GetFunctionPointerForDelegate<XlAct170>((XlAct170)d);
                    case 171:
                        return Marshal.GetFunctionPointerForDelegate<XlAct171>((XlAct171)d);
                    case 172:
                        return Marshal.GetFunctionPointerForDelegate<XlAct172>((XlAct172)d);
                    case 173:
                        return Marshal.GetFunctionPointerForDelegate<XlAct173>((XlAct173)d);
                    case 174:
                        return Marshal.GetFunctionPointerForDelegate<XlAct174>((XlAct174)d);
                    case 175:
                        return Marshal.GetFunctionPointerForDelegate<XlAct175>((XlAct175)d);
                    case 176:
                        return Marshal.GetFunctionPointerForDelegate<XlAct176>((XlAct176)d);
                    case 177:
                        return Marshal.GetFunctionPointerForDelegate<XlAct177>((XlAct177)d);
                    case 178:
                        return Marshal.GetFunctionPointerForDelegate<XlAct178>((XlAct178)d);
                    case 179:
                        return Marshal.GetFunctionPointerForDelegate<XlAct179>((XlAct179)d);
                    case 180:
                        return Marshal.GetFunctionPointerForDelegate<XlAct180>((XlAct180)d);
                    case 181:
                        return Marshal.GetFunctionPointerForDelegate<XlAct181>((XlAct181)d);
                    case 182:
                        return Marshal.GetFunctionPointerForDelegate<XlAct182>((XlAct182)d);
                    case 183:
                        return Marshal.GetFunctionPointerForDelegate<XlAct183>((XlAct183)d);
                    case 184:
                        return Marshal.GetFunctionPointerForDelegate<XlAct184>((XlAct184)d);
                    case 185:
                        return Marshal.GetFunctionPointerForDelegate<XlAct185>((XlAct185)d);
                    case 186:
                        return Marshal.GetFunctionPointerForDelegate<XlAct186>((XlAct186)d);
                    case 187:
                        return Marshal.GetFunctionPointerForDelegate<XlAct187>((XlAct187)d);
                    case 188:
                        return Marshal.GetFunctionPointerForDelegate<XlAct188>((XlAct188)d);
                    case 189:
                        return Marshal.GetFunctionPointerForDelegate<XlAct189>((XlAct189)d);
                    case 190:
                        return Marshal.GetFunctionPointerForDelegate<XlAct190>((XlAct190)d);
                    case 191:
                        return Marshal.GetFunctionPointerForDelegate<XlAct191>((XlAct191)d);
                    case 192:
                        return Marshal.GetFunctionPointerForDelegate<XlAct192>((XlAct192)d);
                    case 193:
                        return Marshal.GetFunctionPointerForDelegate<XlAct193>((XlAct193)d);
                    case 194:
                        return Marshal.GetFunctionPointerForDelegate<XlAct194>((XlAct194)d);
                    case 195:
                        return Marshal.GetFunctionPointerForDelegate<XlAct195>((XlAct195)d);
                    case 196:
                        return Marshal.GetFunctionPointerForDelegate<XlAct196>((XlAct196)d);
                    case 197:
                        return Marshal.GetFunctionPointerForDelegate<XlAct197>((XlAct197)d);
                    case 198:
                        return Marshal.GetFunctionPointerForDelegate<XlAct198>((XlAct198)d);
                    case 199:
                        return Marshal.GetFunctionPointerForDelegate<XlAct199>((XlAct199)d);
                    case 200:
                        return Marshal.GetFunctionPointerForDelegate<XlAct200>((XlAct200)d);
                    case 201:
                        return Marshal.GetFunctionPointerForDelegate<XlAct201>((XlAct201)d);
                    case 202:
                        return Marshal.GetFunctionPointerForDelegate<XlAct202>((XlAct202)d);
                    case 203:
                        return Marshal.GetFunctionPointerForDelegate<XlAct203>((XlAct203)d);
                    case 204:
                        return Marshal.GetFunctionPointerForDelegate<XlAct204>((XlAct204)d);
                    case 205:
                        return Marshal.GetFunctionPointerForDelegate<XlAct205>((XlAct205)d);
                    case 206:
                        return Marshal.GetFunctionPointerForDelegate<XlAct206>((XlAct206)d);
                    case 207:
                        return Marshal.GetFunctionPointerForDelegate<XlAct207>((XlAct207)d);
                    case 208:
                        return Marshal.GetFunctionPointerForDelegate<XlAct208>((XlAct208)d);
                    case 209:
                        return Marshal.GetFunctionPointerForDelegate<XlAct209>((XlAct209)d);
                    case 210:
                        return Marshal.GetFunctionPointerForDelegate<XlAct210>((XlAct210)d);
                    case 211:
                        return Marshal.GetFunctionPointerForDelegate<XlAct211>((XlAct211)d);
                    case 212:
                        return Marshal.GetFunctionPointerForDelegate<XlAct212>((XlAct212)d);
                    case 213:
                        return Marshal.GetFunctionPointerForDelegate<XlAct213>((XlAct213)d);
                    case 214:
                        return Marshal.GetFunctionPointerForDelegate<XlAct214>((XlAct214)d);
                    case 215:
                        return Marshal.GetFunctionPointerForDelegate<XlAct215>((XlAct215)d);
                    case 216:
                        return Marshal.GetFunctionPointerForDelegate<XlAct216>((XlAct216)d);
                    case 217:
                        return Marshal.GetFunctionPointerForDelegate<XlAct217>((XlAct217)d);
                    case 218:
                        return Marshal.GetFunctionPointerForDelegate<XlAct218>((XlAct218)d);
                    case 219:
                        return Marshal.GetFunctionPointerForDelegate<XlAct219>((XlAct219)d);
                    case 220:
                        return Marshal.GetFunctionPointerForDelegate<XlAct220>((XlAct220)d);
                    case 221:
                        return Marshal.GetFunctionPointerForDelegate<XlAct221>((XlAct221)d);
                    case 222:
                        return Marshal.GetFunctionPointerForDelegate<XlAct222>((XlAct222)d);
                    case 223:
                        return Marshal.GetFunctionPointerForDelegate<XlAct223>((XlAct223)d);
                    case 224:
                        return Marshal.GetFunctionPointerForDelegate<XlAct224>((XlAct224)d);
                    case 225:
                        return Marshal.GetFunctionPointerForDelegate<XlAct225>((XlAct225)d);
                    case 226:
                        return Marshal.GetFunctionPointerForDelegate<XlAct226>((XlAct226)d);
                    case 227:
                        return Marshal.GetFunctionPointerForDelegate<XlAct227>((XlAct227)d);
                    case 228:
                        return Marshal.GetFunctionPointerForDelegate<XlAct228>((XlAct228)d);
                    case 229:
                        return Marshal.GetFunctionPointerForDelegate<XlAct229>((XlAct229)d);
                    case 230:
                        return Marshal.GetFunctionPointerForDelegate<XlAct230>((XlAct230)d);
                    case 231:
                        return Marshal.GetFunctionPointerForDelegate<XlAct231>((XlAct231)d);
                    case 232:
                        return Marshal.GetFunctionPointerForDelegate<XlAct232>((XlAct232)d);
                    case 233:
                        return Marshal.GetFunctionPointerForDelegate<XlAct233>((XlAct233)d);
                    case 234:
                        return Marshal.GetFunctionPointerForDelegate<XlAct234>((XlAct234)d);
                    case 235:
                        return Marshal.GetFunctionPointerForDelegate<XlAct235>((XlAct235)d);
                    case 236:
                        return Marshal.GetFunctionPointerForDelegate<XlAct236>((XlAct236)d);
                    case 237:
                        return Marshal.GetFunctionPointerForDelegate<XlAct237>((XlAct237)d);
                    case 238:
                        return Marshal.GetFunctionPointerForDelegate<XlAct238>((XlAct238)d);
                    case 239:
                        return Marshal.GetFunctionPointerForDelegate<XlAct239>((XlAct239)d);
                    case 240:
                        return Marshal.GetFunctionPointerForDelegate<XlAct240>((XlAct240)d);
                    case 241:
                        return Marshal.GetFunctionPointerForDelegate<XlAct241>((XlAct241)d);
                    case 242:
                        return Marshal.GetFunctionPointerForDelegate<XlAct242>((XlAct242)d);
                    case 243:
                        return Marshal.GetFunctionPointerForDelegate<XlAct243>((XlAct243)d);
                    case 244:
                        return Marshal.GetFunctionPointerForDelegate<XlAct244>((XlAct244)d);
                    case 245:
                        return Marshal.GetFunctionPointerForDelegate<XlAct245>((XlAct245)d);
                    case 246:
                        return Marshal.GetFunctionPointerForDelegate<XlAct246>((XlAct246)d);
                    case 247:
                        return Marshal.GetFunctionPointerForDelegate<XlAct247>((XlAct247)d);
                    case 248:
                        return Marshal.GetFunctionPointerForDelegate<XlAct248>((XlAct248)d);
                    case 249:
                        return Marshal.GetFunctionPointerForDelegate<XlAct249>((XlAct249)d);
                    case 250:
                        return Marshal.GetFunctionPointerForDelegate<XlAct250>((XlAct250)d);
                    case 251:
                        return Marshal.GetFunctionPointerForDelegate<XlAct251>((XlAct251)d);
                    case 252:
                        return Marshal.GetFunctionPointerForDelegate<XlAct252>((XlAct252)d);
                    case 253:
                        return Marshal.GetFunctionPointerForDelegate<XlAct253>((XlAct253)d);
                    case 254:
                        return Marshal.GetFunctionPointerForDelegate<XlAct254>((XlAct254)d);
                    case 255:
                        return Marshal.GetFunctionPointerForDelegate<XlAct255>((XlAct255)d);
                }
            }

            throw new NotImplementedException("GetFunctionPointerForDelegate");
        }
    }
}
